# Generated by Django 5.1.4 on 2026-06-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(max_length=255, unique=True)),
                ('message_type', models.CharField(max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qayta ishlangan xabar',
                'verbose_name_plural': 'Qayta ishlangan xabarlar',
                'db_table': 'processed_messages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(db_index=True, max_length=500)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'products',
                'ordering': ['product_name'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
