# Generated by Django 5.1.4 on 2026-07-02 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('caption', models.TextField(blank=True, default='')),
                ('permalink', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram post',
                'verbose_name_plural': 'Instagram postlar',
                'db_table': 'video_posts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentKeywordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=200)),
                ('match_type', models.CharField(choices=[('contains', "O'z ichiga oladi"), ('exact', "To'liq mos"), ('starts_with', 'Boshlanadi')], default='contains', max_length=20)),
                ('public_reply', models.TextField(help_text="Izoh ostida ko'rinadigan javob")),
                ('dm_reply', models.TextField(blank=True, default='', help_text='Direct xabar (ixtiyoriy)')),
                ('send_dm', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Katta raqam — birinchi tekshiriladi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(blank=True, help_text="Bo'sh qoldirilsa — barcha postlarga qo'llanadi", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='shop.videopost')),
            ],
            options={
                'verbose_name': "Izoh kalit so'z qoidasi",
                'verbose_name_plural': "Izoh kalit so'z qoidalari",
                'db_table': 'comment_keyword_rules',
                'ordering': ['-priority', 'keyword'],
            },
        ),
    ]
