# Generated by Django 5.1.4 on 2026-07-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_videopost_commentkeywordrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentkeywordrule',
            name='dm_image',
            field=models.ImageField(blank=True, help_text="Alohida DM rasmi (bo'sh bo'lsa reply_image ishlatiladi)", null=True, upload_to='rule_images/dm/'),
        ),
        migrations.AddField(
            model_name='commentkeywordrule',
            name='reply_image',
            field=models.ImageField(blank=True, help_text='Javob rasmi — Direct xabar orqali yuboriladi', null=True, upload_to='rule_images/'),
        ),
        migrations.AlterField(
            model_name='commentkeywordrule',
            name='dm_reply',
            field=models.TextField(blank=True, default='', help_text='Direct matn xabar (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='commentkeywordrule',
            name='public_reply',
            field=models.TextField(blank=True, default='', help_text="Izoh ostidagi matn javob (ixtiyoriy, rasm bo'lsa ham yozish mumkin)"),
        ),
        migrations.AlterField(
            model_name='commentkeywordrule',
            name='send_dm',
            field=models.BooleanField(default=True, help_text='Rasm yoki DM matn yuborish (izohdan keyin Direct)'),
        ),
        migrations.AlterField(
            model_name='commentkeywordrule',
            name='video',
            field=models.ForeignKey(blank=True, help_text="Qaysi video/post uchun — tanlanmasa barcha postlarga qo'llanadi", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='shop.videopost'),
        ),
    ]
